### DISCUSSION TITLE
feat: yaml support

### DISCUSSION THREAD

**Discussion by brunopgalvao** [r0gue-io/pop-cli#294] [Feature Request]
As a power user, I would like to run `pop new parachain` specifying my parameters using yaml such as:
```
pop new parachain -c config.yml
```
where an example config.yml is:
```yml
name: my_parachain
provider: parity
template: standard
symbol: UNIT
decimals: 12
endowment: "1u64 << 60"

```
