### ISSUE TITLE
HRMP setup doesn't work

### ISSUE THREAD

**Issue by PolkadotDom** [r0gue-io/pop-cli#327]
Hey all, unsure if this is due to differences in zombienet vs the new zombienet sdk or if it's a pop issue, but setting up HRMP channels in the network.toml doesn't appear to work.

Device:
Macbook Air M1

Steps to reproduce
- Install latest POP v.0.4.0
- pop new parachain
- pop build
- pop up parachain -f network.toml

with the following config:
```toml
[relaychain]
chain = "rococo-local"
default_args = [ "-lparachain=debug" ]

[[relaychain.nodes]]
name = "alice"
validator = true
rpc_port = 9944
ws_port = 60930

[[relaychain.nodes]]
name = "bob"
validator = true
rpc_port = 9955
ws_port = 60933

[[parachains]]
id = 2000
default_command = "./target/debug/parachain-template-node"

[[parachains.collators]]
name = "charlie"
rpc_port = 9988
ws_port = 60936
command = "./target/debug/parachain-template-node"

[[parachains]]
id = 2001
default_command = "./target/debug/parachain-template-node"

[[parachains.collators]]
name = "dave"
rpc_port = 9999
ws_port = 60939
command = "./target/debug/parachain-template-node"

[[hrmp_channels]]
sender = 2000
recipient = 2001
max_capacity = 8
max_message_size = 8192

[[hrmp_channels]]
sender = 2001
recipient = 2000
max_capacity = 8
max_message_size = 8192
```

Everything spins up fine. But if you check the relay nodes chainstate hrmp.hrmpchannels between 2000 and 2001 none exist. This configuration works using traditional zombienet spawn -p native

Have checked that the relay configs values for max capacity and max message size are correct. Let me know if any additional info is needed!
