### ISSUE TITLE
Vulnerability dependency

### ISSUE THREAD

**Issue by chungquantin** [r0gue-io/pop-cli#436]
Issue open to track an issue with one of our dependencies when running cargo deny check advisories:

- Advisory: https://rustsec.org/advisories/RUSTSEC-2024-0388
- Original issue: https://github.com/mcarton/rust-derivative/issues/117

# Description

```toml
[advisory]
id = "RUSTSEC-2024-0388"
package = "derivative"
date = "2024-06-26"
url = "https://github.com/mcarton/rust-derivative/issues/117"
informational = "unmaintained"

[versions]
patched = []

```
# `derivative` is unmaintained; consider using an alternative

The [`derivative`](https://crates.io/crates/derivative) crate is no longer maintained.
Consider using any alternative, for instance:
- [derive_more](https://crates.io/crates/derive_more)
- [derive-where](https://crates.io/crates/derive-where)
- [educe](https://crates.io/crates/educe)
