### ISSUE TITLE
Vulnerability dependency

### ISSUE THREAD

**Issue by chungquantin** [r0gue-io/pop-cli#437]
Issue open to track an issue with one of our dependencies when running cargo deny check advisories:

- Advisory: https://rustsec.org/advisories/RUSTSEC-2024-0384.html
- https://crates.io/crates/instant/0.1.13
- https://github.com/sebcrozet/instant/issues/52

### Summary
```toml
[advisory]
id = "RUSTSEC-2024-0384"
package = "instant"
date = "2024-09-01"
references = [
    "https://crates.io/crates/instant/0.1.13",
    "https://github.com/sebcrozet/instant/issues/52",
]
informational = "unmaintained"

[versions]
patched = []
```

# `instant` is unmaintained

This crate is no longer maintained, and the author recommends using the maintained [`web-time`] crate instead.

[`web-time`]: https://crates.io/crates/web-time
