### ISSUE TITLE
Vulnerability dependency

### ISSUE THREAD

**Issue by chungquantin** [r0gue-io/pop-cli#438]
Issue open to track an issue with one of our dependencies when running cargo deny check advisories:

- Advisory: https://rustsec.org/advisories/RUSTSEC-2020-0163.html
- https://github.com/clap-rs/term_size-rs/pull/31

### Summary
```toml
[advisory]
id = "RUSTSEC-2020-0163"
package = "term_size"
date = "2020-11-03"
informational = "unmaintained"
url = "https://github.com/clap-rs/term_size-rs/pull/31"
[versions]
patched = []
unaffected = []
```

# `term_size` is unmaintained; use `terminal_size` instead

The [`term_size`](https://crates.io/crates/term_size) crate is no longer maintained. Consider using
[`terminal_size`](https://crates.io/crates/terminal_size) instead.
