### ISSUE TITLE
Vulnerability dependency

### ISSUE THREAD

**Issue by chungquantin** [r0gue-io/pop-cli#440]
Issue open to track an issue with one of our dependencies when running cargo deny check advisories:

Advisory: https://rustsec.org/advisories/RUSTSEC-2020-0168.html

## Description
```toml
[advisory]
id = "RUSTSEC-2020-0168"
package = "mach"
date = "2020-07-14"
url = "https://github.com/fitzgen/mach/issues/63"
informational = "unmaintained"

[versions]
patched = []
```

# mach is unmaintained

Last release was almost 4 years ago.

Maintainer(s) seem to be completely unreachable. 

## Possible Alternative(s)

These may or may not be suitable alternatives and have not been vetted in any way;
- [mach2](https://crates.io/crates/mach2) - direct fork
