### ISSUE TITLE
Vulnerability dependency

### ISSUE THREAD

**Issue by chungquantin** [r0gue-io/pop-cli#441]
Issue open to track an issue with one of our dependencies when running cargo deny check advisories:

Advisory: https://rustsec.org/advisories/RUSTSEC-2021-0139

## Description
```toml
[advisory]
id = "RUSTSEC-2021-0139"
package = "ansi_term"
date = "2021-08-18"
url = "https://github.com/ogham/rust-ansi-term/issues/72"
informational = "unmaintained"

[versions]
patched = []
```
# ansi_term is Unmaintained

The maintainer has advised that this crate is deprecated and will not receive any maintenance.

The crate does not seem to have much dependencies and may or may not be ok to use as-is.

Last release seems to have been three years ago.

## Possible Alternative(s)

 The below list has not been vetted in any way and may or may not contain alternatives;

 - [ansiterm](https://crates.io/crates/ansiterm)
 - [anstyle](https://github.com/epage/anstyle)
 - [console](https://crates.io/crates/console)
 - [nu-ansi-term](https://crates.io/crates/nu-ansi-term)
 - [owo-colors](https://crates.io/crates/owo-colors)
 - [stylish](https://crates.io/crates/stylish)
 - [yansi](https://crates.io/crates/yansi)

## Dependency Specific Migration(s)

 - [structopt, clap2](https://github.com/clap-rs/clap/discussions/4172)
