### ISSUE TITLE
Vulnerability dependency `frame-benchmarking-cli`

### ISSUE THREAD

**Issue by chungquantin** [r0gue-io/pop-cli#458]

**Comment by chungquantin** [comment]
- Advisories: https://rustsec.org/advisories/RUSTSEC-2024-0336

## Summary

```toml
[advisory]
id = "RUSTSEC-2024-0336"
package = "rustls"
date = "2024-04-19"
url = "https://github.com/rustls/rustls/security/advisories/GHSA-6g7w-8wpp-frhj"
categories = ["denial-of-service"]
aliases = ["CVE-2024-32650", "GHSA-6g7w-8wpp-frhj"]
cvss = "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H"

[versions]
patched = [">= 0.23.5", ">= 0.22.4, < 0.23.0", ">= 0.21.11, < 0.22.0"]

[affected]
functions = { "rustls::ConnectionCommon::complete_io" = ["<= 0.23.4", "<= 0.22.3", "<= 0.21.10", "0.20"] }
```

# `rustls::ConnectionCommon::complete_io` could fall into an infinite loop based on network input

If a `close_notify` alert is received during a handshake, `complete_io`
does not terminate.

Callers which do not call `complete_io` are not affected.

`rustls-tokio` and `rustls-ffi` do not call `complete_io`
and are not affected.

`rustls::Stream` and `rustls::StreamOwned` types use
`complete_io` and are affected.

**Comment by chungquantin** [comment]
- Advisories: https://rustsec.org/advisories/RUSTSEC-2024-0421.html

# Summary

```toml
[advisory]
id = "RUSTSEC-2024-0421"

package = "idna"

date = "2024-12-09"

categories = ["privilege-escalation"]

keywords = ["idna", "punycode", "same-origin", "domain-name"]

aliases = ["CVE-2024-12224"]

url = "https://bugzilla.mozilla.org/show_bug.cgi?id=1887898"

[versions]
patched = [">= 1.0.0"]
```

# `idna` accepts Punycode labels that do not produce any non-ASCII when decoded

`idna` 0.5.0 and earlier accepts Punycode labels that do not produce any non-ASCII output, which means that either ASCII labels or the empty root label can be masked such that they appear unequal without IDNA processing or when processed with a different implementation and equal when processed with `idna` 0.5.0 or earlier.

Concretely, `example.org` and `xn--example-.org` become equal after processing by `idna` 0.5.0 or earlier. Also, `example.org.xn--` and `example.org.` become equal after processing by `idna` 0.5.0 or earlier.

In applications using `idna` (but not in `idna` itself) this may be able to lead to privilege escalation when host name comparison is part of a privilege check and the behavior is combined with a client that resolves domains with such labels instead of treating them as errors that preclude DNS resolution / URL fetching and with the attacker managing to introduce a DNS entry (and TLS certificate) for an `xn--`-masked name that turns into the name of the target when processed by `idna` 0.5.0 or earlier.

## Remedy

Upgrade to `idna` 1.0.3 or later, if depending on `idna` directly, or to `url` 2.5.4 or later, if depending on `idna` via `url`. (This issue was fixed in `idna` 1.0.0, but versions earlier than 1.0.3 are not recommended for other reasons.)

When upgrading, please take a moment to read about [alternative Unicode back ends for `idna`](https://docs.rs/crate/idna_adapter/latest).

If you are using Rust earlier than 1.81 in combination with SQLx 0.8.2 or earlier, please also read an [issue](https://github.com/servo/rust-url/issues/992) about combining them with `url` 2.5.4 and `idna` 1.0.3.

## Additional information

This issue resulted from `idna` 0.5.0 and earlier implementing the UTS 46 specification literally on this point and the specification having this bug. The specification bug has been fixed in [revision 33 of UTS 46](https://www.unicode.org/reports/tr46/tr46-33.html#Modifications).

## Acknowledgements

Thanks to kageshiron for recognizing the security implications of this behavior.

**Comment by chungquantin** [comment]
- Advisories: https://rustsec.org/advisories/RUSTSEC-2025-0010

# Summary

```toml
[advisory]
id = "RUSTSEC-2025-0010"
package = "ring"
date = "2025-03-05"
informational = "unmaintained"
url = "https://github.com/briansmith/ring/discussions/2450"

[versions]
patched = []
unaffected = [ ">= 0.17" ]
```

# Versions of *ring* prior to 0.17 are unmaintained.

*ring* 0.16.20 was released over 4 years ago and isn't maintained, tested, etc.

Additionally, the project's general policy is to only patch the latest release,
which is 0.17.12 now. It will be difficult for anybody to backport future fixes
to versions earlier than 0.17.10 due to license changes.

**Comment by chungquantin** [comment]
- Advisories: https://rustsec.org/advisories/RUSTSEC-2024-0370.html

# Summary

```toml
[advisory]
id = "RUSTSEC-2024-0370"
package = "proc-macro-error"
date = "2024-09-01"
informational = "unmaintained"
url = "https://gitlab.com/CreepySkeleton/proc-macro-error/-/issues/20"

[versions]
patched = []
```

# proc-macro-error is unmaintained

proc-macro-error's maintainer seems to be unreachable, with no commits for 2 years, no releases pushed for 4 years, and no activity on the GitLab repo or response to email.

proc-macro-error also depends on `syn 1.x`, which may be bringing duplicate dependencies into dependant build trees.

## Possible Alternative(s)

- [manyhow](https://crates.io/crates/manyhow)
- [proc-macro-error2](https://crates.io/crates/proc-macro-error2)
- [proc-macro2-diagnostics](https://github.com/SergioBenitez/proc-macro2-diagnostics)

**Comment by chungquantin** [comment]
- Advisories: https://rustsec.org/advisories/RUSTSEC-2025-0014.html

# Summary

```toml
[advisory]
id = "RUSTSEC-2025-0014"
package = "humantime"
date = "2025-03-08"
url = "https://github.com/tailhook/humantime/issues/31"
informational = "unmaintained"

[versions]
patched = []
```

# humantime is unmaintained

Latest `humantime` crates.io release is four years old and GitHub repository has
not seen commits in four years. Question about maintenance status has not gotten
any reaction from maintainer: https://github.com/tailhook/humantime/issues/31

## Possible alternatives

 * [jiff](https://crates.io/crates/jiff) provides same kind of functionality

**Comment by chungquantin** [comment]
- Advisories: https://rustsec.org/advisories/RUSTSEC-2020-0168.html

# Summary

```toml
[advisory]
id = "RUSTSEC-2020-0168"
package = "mach"
date = "2020-07-14"
url = "https://github.com/fitzgen/mach/issues/63"
informational = "unmaintained"

[versions]
patched = []
```

# mach is unmaintained


Last release was almost 4 years ago.

Maintainer(s) seem to be completely unreachable. 

## Possible Alternative(s)

These may or may not be suitable alternatives and have not been vetted in any way;
- [mach2](https://crates.io/crates/mach2) - direct fork

**Comment by chungquantin** [comment]
- Advisories: https://rustsec.org/advisories/RUSTSEC-2025-0017.html

# Summary
```toml
[advisory]
id = "RUSTSEC-2025-0017"
package = "trust-dns-proto"
date = "2025-03-23"
url = "https://crates.io/crates/hickory-proto"
informational = "unmaintained"
references = ["https://github.com/hickory-dns/hickory-dns/issues/2051"]

[versions]
patched = []
unaffected = ["<= 0.23.0"]
```

# The `trust-dns` project has been rebranded to `hickory-dns`

The `trust-dns-proto` crate is now available as `hickory-proto`.
