### ISSUE TITLE
Install the rust version compatible with the chosen polkadot-sdk version

### ISSUE THREAD

**Issue by Moliholy** [r0gue-io/pop-cli#550]
In recent versions of polkadot-sdk, it turns out newer versions of rustc are not able to compile parachain code. That might not be the case in the future, but it's always a possibility. I open this issue simply to suggest the following:

- If the chosen polkadot-sdk version for a parachain project is not using the rustc version polkadot-sdk was guaranteed to be compiled with, then install that particular verssion. Or simply suggest to add a `rust-toolchain.toml` (perhaps when running `pop install`?) file with the following sample contents:

```toml
[toolchain]
profile = "minimal"
channel = "1.84.1"
components = ["rustfmt", "clippy", "rust-src"]
targets = ["wasm32-unknown-unknown"]
```

- Include that file in all templates, or create it once the template is instantiated, if that's not currently the case.
